### ISSUE TITLE
App-deployment

### ISSUE THREAD

**Issue by ikoote1** [ikoote1/Portfolio-Setup#6]
Deployment:
- link= ("  https://ikoote1.github.io/Portfolio-Setup/" )

**Comment by bobb-Rob** [comment]
## STATUS: APPROVED ✔️ 🍾

Hi @ikoote1 , 

Your project is complete!  :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ Deployed page works fine.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this ISSUES FIX. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ikoote1** [comment]
Help me and point at those optional suggestions, I would like to address them, please. 
Thankx.
@bobb-Rob
